### ISSUE TITLE
InstantSerializer incompatible with @JsonSerialize

### ISSUE THREAD

**Issue by sourcekick** [FasterXML/jackson-datatype-jsr310#10]
As the current implementation stands an `InstantSerializer` seemingly cannot be used with the annotation `@JsonSerialize` from package `com.fasterxml.jackson.databind.annotation` .

Respectively `InstantDeserializer` with `@JsonDeserialize`.

Note: An idea may have been to always register the serializer / deserializer instances `INSTANT`, `OFFSET_DATE_TIME` or `ZONED_DATE_TIME` centrally by registering the module `JSR310Module`. However, it would be nicer if the annotations also worked out of the box.

**Comment by beamerblvd** [comment]
It appears this is fixed? Can someone verify so that we can close this?

**Comment by cowtowncoder** [comment]
I think this is closed indeed.
