### ISSUE TITLE
Parsing empty string into ZoneId should fail if ACCEPT_EMPTY_STRING_AS_NULL_OBJECT is disabled

### ISSUE THREAD

**Issue by kopper** [FasterXML/jackson-datatype-jsr310#101]
By default DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT is disabled and parsing ZoneId yields null.

https://github.com/FasterXML/jackson-datatype-jsr310/blob/a2331c200ca1610e13a2048f5037da91aa67409c/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/JSR310StringParsableDeserializer.java#L80

**Comment by kopper** [comment]
3.0 seems to be a better fit, given that nobody else complained so far

**Comment by cowtowncoder** [comment]
Yes, that is probably safer.
