### ISSUE TITLE
Serializers should support `@JsonFormat` annotation for configuration

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatype-jsr310#11]
Similar to how core `java.util.Date` types and (possibly?) Joda types, serializers here should support configurability using `@JsonFormat` annotation.

**Comment by tyoras** [comment]
Adding support of this annotation is useful when you need to serialize / deserialize the LocalDate in another format than ISO-8601.

**Comment by cowtowncoder** [comment]
As far as I can see, support via `@JsonFormat(pattern="format")` already works, at least for `LocalDate`, `LocalDateTime` and `LocalTime`.

**Comment by zkiss** [comment]
@cowtowncoder I think there's still some work to do: https://github.com/FasterXML/jackson-datatype-jsr310/blob/master/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/InstantSerializerBase.java#L65

**Comment by cowtowncoder** [comment]
I'll file a separate issue, assuming there is a way to add custom format support for Instants.
