### ISSUE TITLE
Instant is serialized as String but can't be deserialized (unless manually converted to float)

### ISSUE THREAD

**Issue by aioobe** [FasterXML/jackson-datatype-jsr310#16]
The default Instant serializer performs the following:

    generator.writeNumber(DecimalUtils.toDecimal(
        this.getEpochSeconds.applyAsLong(instant), this.getNanoseconds.applyAsInt(instant)
    ));

This turns up as a String (toDecimal returns String), at least in MongoDB.

During deserialization, the token is a String, so the following code is invoked:

    case VALUE_STRING:
        String string = parser.getText().trim();
        if(string.length() == 0)
            return null;
        if(context.isEnabled(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE))
            return this.adjust.apply(this.parse.apply(string), this.getZone(context));
        return this.parse.apply(string);

which results in 

    java.time.format.DateTimeParseException: Text '1420891051.120000000' could not be parsed at index 0

After manually converting from a String to the corresponding float in MongoDB, the deserialization takes the case `VALUE_NUMBER_FLOAT` and works as expected.

**Comment by cowtowncoder** [comment]
@aioobe I am bit confused about reference to MongoDB: is this via BSON driver (https://github.com/michel-kraemer/bson4jackson)? Or how is MongoDB getting into picture.

**Comment by aioobe** [comment]
Good question. I should have been more clear because not even I can say exactly what it means. But I'm using Jongo and a Jackson mapper for serialization. Does the report make sense to you without the MongoDB reference?

Here's the patch I'm using:

    -                generator.writeNumber(DecimalUtils.toDecimal(
    +
    +                generator.writeNumber(Float.valueOf(DecimalUtils.toDecimal(
    +                        this.getEpochSeconds.applyAsLong(instant),
    +                        this.getNanoseconds.applyAsInt(instant))));
    +                /*
    +                generator.writeNumber(new java.math.BigDecimal(DecimalUtils.toDecimal(
                             this.getEpochSeconds.applyAsLong(instant), this.getNanoseconds.applyAsInt(instant)
    -                ));
    +                )).floatValue());
    +                */

**Comment by cowtowncoder** [comment]
Thanks. I hope to find time to add see what is being tested, and if more unit tests are needed.
That could then help figure whether this is a general problem, or something Mongo-specific.
One challenge is that BSON does support a wide variety of extension types, and so may translate values in unexpected ways on either direction; so it could be possible that something written as a number might surface back as a String. If so, it would differ from handling of basic JSON output where there is strict 1-to-1 mapping.

**Comment by Comparific** [comment]
Ok, I see. Let me know if I can be of any assistance.

**Comment by aioobe** [comment]
Ok I see. Let me know if I can be of any assistance.

**Comment by cowtowncoder** [comment]
@aioobe At this point any help would be appreciated, as I am not sure when I get to look at this particular issue. I am planning to do some more work with this module and Joda one, before 2.6.0, but there are a few other things to finalize for release.

**Comment by cowtowncoder** [comment]
I would still like to learn more about where and how the problem occurs: my best guess is that some combination of things results in a floating-point number being serialized as String instead, and if so, deserializer just assuming it is a textual date/time.
Such a case would be handled with a regexp check first, if need be, but I would rather first have a reproducible problem / test case, before adding speculative (at this point) work-around.

**Comment by aioobe** [comment]
Sorry for the delay. When creating the reproducer I also realized that Jongo (http://jongo.org/) was a part of the stew.

Looking at the stacktrace and the code involved, it seems to me like the problem is in `com/fasterxml/jackson/datatype/jsr310/ser/InstantSerializerBase.java` (but I may be wrong on that point).

Here's a reproducer: https://gist.github.com/aioobe/bc8039e4e94dbaadc345

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by lukelukeluke** [comment]
+1. Jackson serializes an instant as a string but can't deserialize the same string.

**Comment by aioobe** [comment]
@cowtowncoder, any progress on this issue?

**Comment by cowtowncoder** [comment]
@aioobe Test case seems to be for Jackson 2.4.0. I can not reproduce it with 2.7.0.

**Comment by cowtowncoder** [comment]
Added handling for 'number as String'. Fix for 2.6(.6), 2.7.1.
