### ISSUE TITLE
2.5.2 throws ClassNotFoundException in OSGi

### ISSUE THREAD

**Issue by dukeyin** [FasterXML/jackson-datatype-jsr310#21]
`objectMapper.registerModule(new JSR310Module());` causes a chain of ClassNotFoundExceptions.  It was previously working in 2.4.2.

The classes that cannot be found were in non-imported packages such as:
com.fasterxml.jackson.databind.deser
com.fasterxml.jackson.databind.ser

**Comment by cowtowncoder** [comment]
That is odd. I thought OSGi plug-in would have auto-imported what is needed. Apparently not.
