### ISSUE TITLE
Error while using InstantDeserializer

### ISSUE THREAD

**Issue by robertrv** [FasterXML/jackson-datatype-jsr310#23]
I am trying to do the following 

```java
    @JsonSerialize(using=InstantSerializer.class, include=JsonSerialize.Inclusion.NON_NULL)
    @JsonDeserialize(using=LocalDateDeserializer.class)
    private final java.time.Instant createdDate;
```

The part of the Serializer works fine but the Deserializer shows a compilation error like:

```
Error:(49, 47) java: incompatible types: java.lang.Class<com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer> cannot be converted to java.lang.Class<? extends com.fasterxml.jackson.databind.JsonDeserializer<?>>
```

I think this has to do with the class generic. Not sure if I am doing it properly.

I am using Jackson 2.4.x to do this code & java 8.

**Comment by cowtowncoder** [comment]
Hmmh. Maybe Java 8 compiler does some new checks? Are you compiling this on an IDE, or from command-line?

**Comment by robertrv** [comment]
Just on the IDE.

**Comment by cowtowncoder** [comment]
It could be a setting that converts certain warnings into errors -- as far as I know it should be legal to specify annotations that way. Especially given that there isn't any way to do casting.
So I would try to see configuration of warnings: I can't see anything wrong in your usage, or the way Jackson annotations work in this case.

**Comment by robertrv** [comment]
I was able to reproduce the same from command line. There is the code I was using: https://gist.github.com/robertrv/bbc96c7253ea29910528 

I'll probably create a github repo with maven and so. 

The output from maven:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project Simple: Compilation failure: Compilation failure:
[ERROR] /home/local/ANT/viquer/dvl/tmp/PlayingSimple/src/main/java/com/example/SimplePojo.java:[33,42] error: incompatible types: Class<InstantSerializer> cannot be converted to Class<? extends JsonSerializer<?>>
[ERROR] /home/local/ANT/viquer/dvl/tmp/PlayingSimple/src/main/java/com/example/SimplePojo.java:[34,46] error: incompatible types: Class<InstantDeserializer> cannot be converted to Class<? extends JsonDeserializer<?>>
[ERROR] -> [Help 1]
```

Notice that doesn't happen with LocalDateTimeSerializer or LocalDateTimeDeserializer

**Comment by robertrv** [comment]
https://github.com/robertrv/PlayingSimple

**Comment by cowtowncoder** [comment]
If true, it might be something we can't do much about.

**Comment by robertrv** [comment]
I don't understand. If we can have the LocalDateTimeSerializer/Deserializer why can't we have the same for InstantSerializer/Deserializer? I assumed is just the way the inheritance is done at this class, isn't it?

**Comment by cowtowncoder** [comment]
I meant that if you compiler gives an error for case that really should not cause any kind of error.
I really do not see why or how this should be problematic, or how to work around the issue.

**Comment by robertrv** [comment]
seems that in fact this is the same issue that #10 . I understand that is a bit of a problem having to create extra classes due this. The same that you did for InstantSerializer I guess can be done for InstantDeserializer

**Comment by cowtowncoder** [comment]
If my memory serves me, that was more with the inability of the (de)serializer to actually work, but not about compilation failing.

**Comment by cowtowncoder** [comment]
Problem is that definition of `using` should just say "Sub-class of JsonSerializer" (or JsonDeserializer etc, in different cases). Compiler should not fuzz about this, given that annotation types can not use nominal type parameters; nor does it have any means to even validate meaning on compilation, much less then when reading bytecode. And I have not seen this problem pre-Java8, although given that this module is Java8 only, it's hard to know if it could happen with earlier versions.

If I find a way to address this on declarative side I can try to get change in 2.6. But it is peculiar thing all around...

**Comment by cowtowncoder** [comment]
Hmmh. But maybe I could eliminate type parameter from `InstantDeserializer`. Let's see.

**Comment by cowtowncoder** [comment]
No. It goes deeper than that: even eliminating type parameters will not make compiler happy. Piece of .... work.

However: it is true that even if assigment worked, there is no zero-argument constructor, which means that it's as well that annotation does not compile, because it would be impossible to construct instance.

So in that sense, yes, this is indeed similar to #10. As witnessed by sample project working better with 2.5.x, compared to 2.4.x.

**Comment by cowtowncoder** [comment]
Actually I think my fix for https://github.com/FasterXML/jackson-databind/issues/812 should resolve this issue for 2.6.0.

**Comment by jason-o** [comment]
I have the same issue with
@JsonDeserialize(using = ZonedDateTimeKeyDeserializer.class)

Error:
Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: java.time.ZonedDateTime cannot be cast to org.joda.time.DateTimeZone (through reference chain: com.altec.service.service_ticket.ServiceTicketType["dateReported"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: java.time.ZonedDateTime cannot be cast to org.joda.time.DateTimeZone (through reference chain: com.altec.service.service_ticket.ServiceTicketType["dateReported"])

Anyone find an actual workaround for this?

**Comment by cowtowncoder** [comment]
@jason-o it is not clear that your issue is the same, so please do not add it to closed issue here.

You also may want to read the exception message more carefully: it points out that you appear to try to use Java 8 deserializer with Joda type.

And finally, there is no work-around here: use of these deserializers via annotations is not a supported mechanism; they are designed to be used via module registrations.

**Comment by jason-o** [comment]
removed

Thank you for your response

Regards,
*Jason Ory*
Senior Software Developer
Certified Salesforce Platform Developer I
