### ISSUE TITLE
ZoneId type information improperly handled when default typing enabled

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatype-jsr310#24]
(note: moved from https://github.com/FasterXML/jackson-databind/issues/786; reported by @jedvardsson)

-----

Jackson fails to serialize/deserialize objects when using default typing even though a custom serializer/deserializer is provided. I stumbled upon this when using JSR310Module together with default typing. I'm unsure if this is a databind problem or a problem with the JSR310Module.

Code to reproduce:

        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JSR310Module());
        mapper.enableDefaultTyping();

        ZoneId id = ZoneId.of("America/Chicago");

        String value = this.mapper.writeValueAsString(id);
        ZoneId id2 = this.mapper.readValue(value, ZoneId.class);

        assertEquals("The value is not correct.", id, id2);

Gives the following error:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_STRING), expected START_ARRAY: need JSON Array to contain As.WRAPPER_ARRAY type information for class java.time.ZoneId
 at [Source: "America/Chicago"; line: 1, column: 1]
```

**Comment by cowtowncoder** [comment]
Ah. This is tricky, but basically comes down to this:

1. `ZoneId` is an abstract type, and as such should add type info, if type is known: this happens during deserialization, where type information is expected
2. Value `id`, however, is of concrete type `ZoneRegion`, which extends/implements `ZoneId`: so type used for serialization is NOT abstract but concrete
3. No type id is added to concrete type.

The problem there would be that type used for serialization differs from type expected in deserialization.
The first fix idea would be to use:

        String json = mapper.writerFor(ZoneId.class).writeValueAsString(exp);

to force use of `ZoneId` as the base type. And this does add type information.

Alas, it then causes problems on deserialization side because class `ZoneId` can not be instantiated.

Another theoretical fix would be to add sort of alias to indicate that abstract type `ZoneId` ought to be mapped to `ZoneRegion`. Unfortunately, this will not work as `ZoneRegion` is not a public type, and so can not be referred by the module.

So at this point I am not quite sure how to fix this problem.

**Comment by cowtowncoder** [comment]
One possible work-around: define custom `TypeResolverBuilder` (possibly extend `DefaultTypeResolverBuilder`), to include type id also for `ZoneRegion`, despite it being concrete.
But that needs to be done from application code, checking the actual class name, since there is no good way for modules to indicate such "concrete/impl" pairs to be used with polymorphic deserialization.

That is not an ideal fix, but I mention it as one potential work-around.

**Comment by beamerblvd** [comment]
It seems to me that there needs to be a way to specify factory methods for types. The factory method for `ZoneId` is `ZoneId.of`.

**Comment by cowtowncoder** [comment]
@beamerblvd Unfortunately there is no mechanism to provide that, at this point. That is, no mechanism to associate an external factory for a class. I agree that this would be nice to have, since this pattern is relatively common.

But I wonder if it'd be possible to specify custom `ValueInstantiator` to do just this... Actually that may be the way to go. `Module`s can register `ValueInstantiators`, which is called to provide a `ValueInstantiator`. And that way... yes, I think I'll see if that could be made to work.

**Comment by cowtowncoder** [comment]
I really hate the fact that `ZoneRegion` is hidden.

I suspect there are many ways to go here actually. One is to denote how to construct `ZoneRegion` (via `TimeZone`... ugh); another to try to "downgrade" type id from ZR to ZI AND show how to instantiate it.

For longer term I think I will want to figure out plan b, perhaps by an annotation (and equivalent) to indicate what is a natural base type for a polymorphic class. Perhaps this could even be derived from `@JsonTypeInfo` in most cases.
But this probably won't be available to solve this particular issue, so I think I'll rather try to resolve it only on deserialization side, for now.

**Comment by cowtowncoder** [comment]
Looking at this now, solution is actually Wrong. Type id really should not be optional; this should only be allowed for natural types; and for JSON String that only means `java.lang.String`.
But given the problems discussed above, I will reluctantly leave the hack in place.
