### ISSUE TITLE
Make `ZonedDateTime` serializer support  `SerializationFeature.WRITE_DATES_WITH_ZONE_ID`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatype-jsr310#30]
With introduction of the new `JavaTimeModule`, it is possible to change the defaults.
But although javadocs say that difference is simple matter of changing `SerializationFeature.WRITE_DATES_WITH_ZONE_ID`, it looks like current `ZonedDateTimeSerializer` (and its deprecated counterpart) do not actually use that feature for anything.
This should be changed.

Note that it is not certain whether feature may or should supported for custom date formats specified with `@JsonFormat` (or via per-type module defaults, added for next version).

**Comment by cowtowncoder** [comment]
@zkiss I hope I didn't misread the code (or forget relevant part of discussion), but looks like there's this small part missing. If so, it'd be important to get that available for 2.6.0.

**Comment by zkiss** [comment]
@cowtowncoder yes you are absolutely correct, this feature needs implementing and it would make sense to get it in 2.6.0. Is there a timeline for the release date? I haven't got much free time nowadays, but I think I might be able to get it done in the next couple of weeks.

**Comment by cowtowncoder** [comment]
Timing is such that I just got 2.6.0-rc3 out, but will be having small vacation. So all in all, release will not occur before July 10th or so. And if I know in advance, I can wait for couple of days for one or two critical fixes too. I may try tackling this myself too, if you (or someone else) hasn't had time; seems like a relatively straight-forward thing to do, although need time and focus to do it right of course.
