### ISSUE TITLE
Exceptions when upgrading from 2.5.2 to 2.6.0-rc3

### ISSUE THREAD

**Issue by pluttrell** [FasterXML/jackson-datatype-jsr310#33]
When upgrading from jackson-datatype-jsr310:2.5.2 to 2.6.0-rc3 with the following code:

```
ObjectMapper objectMapper = new ObjectMapper();

    objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    objectMapper.configure(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN, true);
    objectMapper.configure(JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS, true);

    objectMapper.registerModule(new JSR310Module());
```

I encounter this exception:

```
Caused by: java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.ser.std.StdSerializer.<init>(Ljava/lang/Class;)V from class com.fasterxml.jackson.datatype.jsr310.JSR310Module
	at com.fasterxml.jackson.datatype.jsr310.JSR310Module.<init>(JSR310Module.java:143)
```

**Comment by pluttrell** [comment]
The same is true with the `JavaTimeModule`.

```
Caused by: java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.ser.std.StdSerializer.<init>(Ljava/lang/Class;)V from class com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
	at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:159)
```

**Comment by cowtowncoder** [comment]
Is it possible you might have inconsistent minor version of some of the components? Like 2.5 of databind, 2.6.x of jsr310 module?

**Comment by pluttrell** [comment]
Here's what I'm using for those I believe relevant:

```
compile 'com.fasterxml.jackson.core:jackson-core:2.6.0-rc3'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.6.0-rc3'
compile 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.5.2' //v2.6.0-rc3 does not work.
compile 'com.fasterxml.jackson.module:jackson-module-guice:2.6.0-rc3'
```

**Comment by cowtowncoder** [comment]
You seem to be missing explicit `jackson-databind`. That's where `StdSerializer` comes from.
If so, it will be gotten via transitive dependencies, and neither core nor annotations depends on it, so it may be resolved to an older version through something else.

**Comment by pluttrell** [comment]
I just added that additional dependency, but still have the same problem.

My Jackson related dependencies are now:

```
compile 'com.fasterxml.jackson.core:jackson-core:2.6.0-rc3'
compile 'com.fasterxml.jackson.core:jackson-databind:2.6.0-rc3'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.6.0-rc3'
compile 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.6.0-rc3'
compile 'com.fasterxml.jackson.module:jackson-module-guice:2.6.0-rc3'
```

And in my assembled EAR, I have these Jackson JARs:
* jackson-core-2.6.0-rc3.jar
* jackson-databind-2.6.0-rc3.jar
* jackson-annotations-2.6.0-rc3.jar
* jackson-datatype-jsr310-2.6.0-rc3.jar
* jackson-module-guice-2.6.0-rc3.jar

**Comment by cowtowncoder** [comment]
That is peculiar, as the problem really can only occur (as far as I can see) due to incompatibility of some kind... what platform is this on?

**Comment by pluttrell** [comment]
OS: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64)
AppServer: WildFly 8.2.0.Final
Deploy JVM: Oracle Java8u25
Build JDK: Oracle Java8u45

**Comment by cowtowncoder** [comment]
My only lead at this point is that Java 8 has exposed some odd incompatibilities in some areas: for example, handling of generic classes for annotation values. But even there the error message is quite specific and suggests mismatch between compiled version of databind jar, deployed version.

Is there any chance that you might have 2 copies of `jackson-databind` in classpath?

**Comment by ryantenney** [comment]
@pluttrell I believe I have encountered the same issue. You need to create a file at `WEB-INF/jboss-deployment-structure.xml` containing the following to instruct JBoss to not load its copy of Jackson:
```xml
<jboss-deployment-structure>
	<deployment>
		<exclusions>
			<module name="org.jboss.resteasy.resteasy-jackson2-provider"/>
		</exclusions>
	</deployment>
</jboss-deployment-structure>
```

**Comment by cowtowncoder** [comment]
@ryantenney thank you for sharing this.

That would explain the problem, I think, if 2 incompatible copies of `jackson-databind` existed.
Unfortunate, but at least not from Twilight Zone, that is, logical.

**Comment by russray2008** [comment]
Thank you @ryantenney.  Your suggestion helped me solved my error when I was deploying to wildfly8.2.0.Final.

**Comment by kouddy** [comment]
@ryantenney You suggestion helped me with wildfly8.2.0 Final as well. Thanks!

**Comment by bmiddleb** [comment]
Unfortunately, this doesn't resolve it for GlassFish 4.0.1 (aka 4.1). Any ideas?

**Comment by cowtowncoder** [comment]
@bmiddleb In general it is due to a version discrepancy so you need to see that `jackson-databind` and `jackson-datatype-jsr310` have same minor versions.
