### ISSUE TITLE
LocalTimeDeserializer does not use configured formatter

### ISSUE THREAD

**Issue by time4tea** [FasterXML/jackson-datatype-jsr310#35]
```java
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HHmmssSSS")
    public LocalTime time;
```

LocalTimeDeserializer.java

    return LocalTime.parse(string);

OffsetTimeDeserializer.java

    return OffsetTime.parse(string, _formatter);

**Comment by cowtowncoder** [comment]
Is this with version 2.6.0?

**Comment by time4tea** [comment]
Yes.

**Comment by cowtowncoder** [comment]
I am guessing this would be same as #37?

**Comment by time4tea** [comment]
nope, thats localdate, this is localtime.

**Comment by cowtowncoder** [comment]
Ah ok right, should have read your description with more thought. :)

**Comment by time4tea** [comment]
There was a commit that attempted to do this, but the tests don't seem to be strong enough, as deserializing an iso_time can be done (it is the default). I suspect if you pass in a format that is not compatible with the default, it the test wwill fail.

https://github.com/FasterXML/jackson-datatype-jsr310/commit/ba46f10b9d7b1f2209d8262acaf190a7309ea9a1

**Comment by time4tea** [comment]
No test though...

**Comment by time4tea** [comment]
Thanks!

**Comment by cowtowncoder** [comment]
Yeah. Sorry, feeling lazy today.
