### ISSUE TITLE
Missing ZonedDateTime deserializer?

### ISSUE THREAD

**Issue by kenwdelong** [FasterXML/jackson-datatype-jsr310#41]
Why is there a ZonedDateTimeSerializer but no ZonedDateTimeDeserializer?

**Comment by cowtowncoder** [comment]
If you look at `JavaTimeModule`, you will notice that deserialization of `ZonedDateTime` is handled by specifically configured `InstantDeserializer`. I think the original design had similarly unified serializers, but it was refactored out to separate classes for some reason (to simplify implementation most likely).
