### ISSUE TITLE
Expose API to set DateTimeFormatter for de/serialization of ZonedDateTime

### ISSUE THREAD

**Issue by the4yeast** [FasterXML/jackson-datatype-jsr310#43]
Currently, there seems to be no way of doing it, so custom de/serializers must be used, which pretty much eliminates the benefits of JSR310Module.

**Comment by cowtowncoder** [comment]
Just to make sure I understand: is the intent here to support use of `@JsonFormat` (wrt TimeZone, locale, pattern)?

Looking at code, it looks as if configuration was allowed for both serialization and deserialization.

Or are you hoping to reconfigure (de)serializers explicitly during registration of module?

**Comment by heruan** [comment]
I think @the4yeast means that a `ZonedDateTime` gets serialized to a hardcoded format, e.g.
```
2016-02-29T12:44:52.040+01:00[Europe/Rome]
```
and I'm also trying to figure out how to set a different format, since I need just this:
```
2016-02-29T12:44:52.040+01:00
```
and I'm currently forced to use customer de/serializers.

**Comment by cowtowncoder** [comment]
@heruan have you tried using `@JsonFormat`? (with version 2.7.x)

**Comment by heruan** [comment]
Okay, I've found what was wrong: I had a call to `ObjectMapper.findAndRegisterModules()` and it was registering the old `Jsr310Module` instead of the new `JavaTimeModule` which has a configurable `ZonedDateTime` formatter upon registering. Thank you!

**Comment by the4yeast** [comment]
My apologies for not replying sooner, I must have missed the notification :(

Yes, I meant what @heruan said. 

With `JavaTimeModule `in mind - am I missing something? Using a wrong version? Can't see the configuration for the formatted.

**Comment by cowtowncoder** [comment]
@the4yeast What I have been asking has been whether you have tried using `@JsonFormat` annotation on a `ZonedDateTime` valued property. That should work. There is no global configuration available for doing this, yet (there are plans, but no code yet).

**Comment by the4yeast** [comment]
No I didn't, and - even if it works - it's not a viable solution for me - way too many fields in my codebase, many fields in 3rd party code - a global setting would get the job done much easier.

**Comment by cowtowncoder** [comment]
@the4yeast Ok. So that part is not broken. I just want to make sure it is possible at all, first.

**Comment by ruhkopf** [comment]
I also need this feature. Trying to implement the workaround from [JDK bug 8031085](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8031085), which requires a specific formatter setting. I don't think this setting is possible just by using `@JsonFormat` (Please correct me if wrong). 

The JDK bug is pretty annoying; for example, I can't deserialize values such as
`2016-06-03T16:17:10.666+0000`.

**Comment by cowtowncoder** [comment]
Jackson 2.8 does indeed support per-type defaulting of anything that `@JsonFormat` supports; and `pattern` specifically is used to construct formatter instance to use. This default overrides global defaults, but may further be overridden by per-property annotation, if any.

Mechanism to use is via `ObjectMapper`, new method `configOverride(Class<?> type)`, changing settings of returned `ConfigOverride` object.
Some discussion on:

https://github.com/FasterXML/jackson-databind/issues/621

(except change "ignored type" to "format settings")

@ruhkopf If simple setting of pattern is not sufficient, you will need custom deserializer. I don't think there will ever be configuration setting that could allow use of actual code for defining it.

**Comment by cowtowncoder** [comment]
As per previous note, it is now possible to specify format to use without annotations, using Jackson 2.8 "configOverride" as noted above. It works like so:

```java
        ObjectMapper mapper = newMapper();
        mapper.configOverride(LocalDate.class) // and similarly other types
            .setFormat(JsonFormat.Value.forPattern("yyyy_MM_dd"));

```
