### ISSUE TITLE
Problem Deserializing java.time.OffsetTime

### ISSUE THREAD

**Issue by crowmagnumb** [FasterXML/jackson-datatype-jsr310#45]
I have a pair of objects that looks something like ...

    public class Object1 {
        private String name;
        private List<Object2> objects;
    }
 
    public class Object2 { 
        private java.time.LocalDate partDate;
        private java.time.OffsetTime starttime;
        private java.time.OffsetTime endtime;
        private String comment;
    }

where I have left out the only the getters and setters. The only constructors are the default constructors for each. I am using Spring Boot 1.2.6-RELEASE and versions 2.6.2 of databind and this datatype in a maven project. I can serialize Object1 to JSON just fine through a rest GET call  but when I try to deserialize it through a rest PUT I get a bizarre result. I only have one Object2 in the list, my JSON looks like this...

    {"name":"test","objects":[{"partDate":[2015,10,13],"starttime":[15,7,"+0"],"endtime":[2,14,"+0"],"comments":"in the comments"}]}

...and yet I get an Object1 with a list of Object2's of size 3!!

The first Object2 has the partDate and the starttime values, the second one has *just* the endtime value (all other values null), and the third Object2 has just the comment (all other values null). If I send null for the OffsetTime's as it works fine though, I only get one Object2. Or if I null just one of them I get 2 Object2's.

So, it seems that the deserialization of the OffsetTime triggers a "next object" call when iterating through the JSON array.

**Comment by cowtowncoder** [comment]
Sounds like a possible bug. Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Yes, you were absolutely right; code was not properly checking for `JsonToken.END_ARRAY`, leaving stream pointing in wrong position.

**Comment by crowmagnumb** [comment]
Cheers!
