### ISSUE TITLE
In java8 LocalDateTime deserializer "Z" is not accepted

### ISSUE THREAD

**Issue by dmiorandi** [FasterXML/jackson-datatype-jsr310#49]
In java8 LocalDateTime deserializer "Z" is not accepted but it works doing an override of deserializer like this (using original one but with different formatter to allow "Z").

```java 
javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(DateTimeFormatter.ISO_DATE_TIME));
```

Question is could be this modify adopted in main release as default?

you find more details on #14 
```java 
@Service 
@Provider
public class ObjectMapperContextResolver implements ContextResolver<ObjectMapper> {  
    private final ObjectMapper mapper;

    public ObjectMapperContextResolver() {
        mapper = new ObjectMapper();
        JavaTimeModule javaTimeModule=new JavaTimeModule();
        // Hack time module to allow 'Z' at the end of string (i.e. javascript json's) 
        javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(DateTimeFormatter.ISO_DATE_TIME));
        mapper.registerModule(javaTimeModule);
    }

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return mapper;
    }  
}
```

**Comment by cowtowncoder** [comment]
I think that use of timezone indicator for local, non-timezone-bound values is bit misleading so I am not convinced that should work out of the box. There is a way to specify format using `@JsonFormat` annotation for specific property, and it is possible to override registration as well.
In future there are plans to allow per-type override without having to override serializer/deserializer registration as well, and I think that is ultimately to go for this feature.

So I will close this issue for now; there are other issues (at least one for `jackson-databind`, possibly one here) to make per-type format defaulting added in Jackson 2.8.
