### ISSUE TITLE
Instant schema is incorrect

### ISSUE THREAD

**Issue by osi** [FasterXML/jackson-datatype-jsr310#50]
InstantSerializerBase should override JSR310FormattedSerializerBase._acceptTimestampVisitor

The default implementation of _acceptTimestampVisitor indicates the schema is an array of integers, whereas an Instant is either a long or decimal depending on the WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS flag

**Comment by cowtowncoder** [comment]
Makes sense, fixed.
