### ISSUE TITLE
LocalDateTimeSerializer default constructor should use the same formatter as LocalDateTimeDeserializer

### ISSUE THREAD

**Issue by aymanche** [FasterXML/jackson-datatype-jsr310#54]
`LocalDateTimeSerializer`  default constructor currently sets null for formatter ,while `LocalDateTimeDeserializer` default constructor uses `DateTimeFormatter.ISO_LOCAL_DATE_TIME`.
This causes LocalDateTimeSerializer to use `LocalDateTime.toString()` method,which differently formats  ,e.g. '2015-12-16 00:00:00'. The `LocalDateTime.toString()` method will format it as "2015-12-16T00:00" while DateTimeFormatter.ISO_LOCAL_DATE_TIME as "2015-12-16".
Unfortunatley "2015-12-16T00:00" can not be parsed by using the `Date` class deserializer `DateSerializer`

**Comment by cowtowncoder** [comment]
Sounds wrong to me. Would it be possible to get a unit test to reproduce this? That would make it easier to fix, and guard against regressions.
Also would be easier to verify versions affected; I assume that might be all versions up until latest (2.7.0-rc2).

**Comment by aymanche** [comment]
Hi,
well i guess it would be something like this with our configuration of objectmapper
```java
package de.digitalperformance.chargeback.dispute.core.payment;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.deser.std.DateDeserializers;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.DateSerializer;
import com.fasterxml.jackson.databind.util.ISO8601DateFormat;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.Date;
import org.junit.Assert;
import org.junit.Test;

public class LocalDateTimeSerializationTest {

    @Test
    public void deserializeToDate() throws IOException {
        ObjectMapper objectMapper=new ObjectMapper();
        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        final SimpleModule module = new SimpleModule();
        module.addDeserializer(Date.class, new DateDeserializers.DateDeserializer());
        objectMapper.registerModule(module);
        objectMapper.registerModule(new JavaTimeModule());
        String localDateTimeJson=objectMapper.writeValueAsString(LocalDateTime.of(1999,10,10,0,0,0));
        System.out.println(localDateTimeJson);
        Date date=objectMapper.readValue(localDateTimeJson,Date.class);
    }
}

```

The thing is that on server side we serialize LocalDateTime but on client side we deserialize to Date.
It could be that our configuration is wrong.

**Comment by cowtowncoder** [comment]
One thing to note on use of `java.util.Date`: since it does not have `TimeZone` associated with it, internally, there are often issues in getting unexpected timezone, so mixing of these two types is probably something to avoid if possible.

However, the original situation may be problematic, as you state: use of `toString()` is often not optimal.
But at the same time, backwards compatibility is a tricky thing and I would want to minimize risk of breaking existing code... and this gets quite complicated.

So I'll have to think about the right approach here.

**Comment by zkiss** [comment]
To me this seems to be a `LocalDateTime` -> `String` -> `Date` conversion issue. In the generic case a `LocalDateTime` will be formatted as `yyyy-MM-dd'T'hh:mm:ss` (or very similar) by either `LocalDateTime.toString()` or `DateTimeFormatter.ISO_LOCAL_DATE_TIME` and the way the client seems to be set up to parse `Strings` to `Date` does not seem to understand that format.

**Comment by aymanche** [comment]
Hi,
first thanks for the answers.
And in the end we solved it by using LocalDateTime on both sides.
>
In the case of 2015-12-16T00:00 DateTimeFormatter.ISO_LOCAL_DATE_TIME seems to merely chop off the zeroes, because the meaning is the same, but in the case of 2015-12-16 13:37:56 the output would be 2015-12-16T13:37:56 which I'd expect to fail in a similar manner.
>
Actually when seconds are not chop off the Date deserializer would not fail.

**Comment by cowtowncoder** [comment]
Fixed serializers of both `LocalTime` and `LocalDateTime`. I think default `toString()` does slight optimization to drop of unnecessary `:00` at the end, when it is able to; at least that is the only difference from testing perspective. Probably good to change at any rate.
