### ISSUE TITLE
Add support for `@JsonFormat` for `MonthDay`

### ISSUE THREAD

**Issue by StasKolodyuk** [FasterXML/jackson-datatype-jsr310#57]
@JsonFormat doesn't work with MonthDay fields.
Thus, we get ugly "--MM-dd" strings.

**Comment by cowtowncoder** [comment]
@StasKolodyuk Is there an applicable formatter to use with it? This sounds like a good improvement idea if so.

And Pull Requests are always welcome of course. :)

**Comment by cowtowncoder** [comment]
Hmmh. Currently serialization happens using `toString()` method, so we'd need an explicit serializer.

**Comment by StasKolodyuk** [comment]
Great Job, @cowtowncoder , thank you : )
