### ISSUE TITLE
jackson-datatype-jsr310  don't include the license file

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-datatype-jsr310#71]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by cowtowncoder** [comment]
As per maven conventions, added `src/main/resources/META-INF/LICENSE`, verified that it gets included in jar. Thank you for reporting the problem.
