### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-datatype-jsr310#72]
The following source files are without license headers. Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/JSR310DateTimeDeserializerBase.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/DurationKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/InstantKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/Jsr310KeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/LocalDateKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/LocalDateTimeKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/LocalTimeKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/MonthDayKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/OffsetDateTimeKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/OffsetTimeKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/PeriodKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/YearKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/YearMothKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/ZonedDateTimeKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/ZoneIdKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/key/ZoneOffsetKeyDeserializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/OffsetDateTimeSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/JSR310SerializerBase.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/ZonedDateTimeSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/ZonedDateTimeWithZoneIdSerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/Jsr310NullKeySerializer.java
./src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java

./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalDateSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestYearMonthSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalDateKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestOffsetTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestDurationSerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestMonthDayKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestDurationDeserialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestYearKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestZonedDateTimeSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestDecimalUtils.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestZoneIdKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestPeriodKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestOffsetDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestLocalDateKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestOffsetTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestDurationSerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestMonthDayKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestDurationDeserialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestYearKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestDecimalUtils.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestZoneIdKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestPeriodKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestOffsetDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestNullKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestInstantKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestZoneOffsetKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/PolymorphicTest.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/ModuleTestBase.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestZonedDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestLocalDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestYearMonthKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestDurationKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/old/TestLocalTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestNullKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestYearSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestInstantKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestZoneOffsetKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/PolymorphicTest.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/ModuleTestBase.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalTimeSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestZonedDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalDateTimeKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestYearMonthKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalDateTimeSerializationWithCustomFormatter.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestDurationKeySerialization.java
./src/test/java/com/fasterxml/jackson/datatype/jsr310/TestLocalTimeKeySerialization.java

Thanks in advance

**Comment by cowtowncoder** [comment]
No. We do not add boilerplate copyright or license information into source files for Jackson project.
