### ISSUE TITLE
Class com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer has no default (no arg) constructor

### ISSUE THREAD

**Issue by igorgsh** [FasterXML/jackson-datatype-jsr310#75]
jackson datatype-jsr310 ver 2.7.3 (also checked for 2.7.0)
I have build example from "Error while using InstantDeserializer #23" [sources here](https://gist.github.com/robertrv/bbc96c7253ea29910528). It is working well and doesn't throw any exception. Then I commented line 31 `@JsonIgnore` to add Instant field to serialization. It is serialized well as "instant":1461070207.180000000". But the exception throw during deserialization:
`com.fasterxml.jackson.databind.JsonMappingException: Class com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer has no default (no arg) constructor
 at [Source: {"local":[2016,4,19,15,50,7,120000000],"instant":1461070207.180000000}; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:251)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3785)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)`

**Comment by cowtowncoder** [comment]
Would it be possible to provide a smaller self-contained test for this?

**Comment by igorgsh** [comment]
Sure. I have prepared a simple example. 
[Serialization.zip](https://github.com/FasterXML/jackson-datatype-jsr310/files/227216/Serialization.zip)
It contains a maven config and tests. So, run: mvn package  to get result.

**Comment by cowtowncoder** [comment]
@igorgsh thank you!

**Comment by cowtowncoder** [comment]
Ok... Not exactly sure why there are explicit annotations for serializer, deserializer. They are registered by jsr310 module and there is no need to try to register them explicitly. Further, as exception points out, `InstantDeserializer` does not indeed have a zero-argument constructor. Without one there is no way for Jackson to create an instance via these annotations.

So I would just remove `@JsonSerialize` and `@JsonDeserialize` annotations and use module registrations. Or, if you don't want automatic registration that way, you can implement `Module` and handle registration that way.

**Comment by igorgsh** [comment]
I have used Java8:
C:\Users\Me>java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

C:\Users\Me>javac -version
javac 1.8.0_77

**Comment by cowtowncoder** [comment]
Right, as per my earlier note, get rid of those `@JsonSerialize` and `@JsonDeserializer` annotations, and handling should work as expected. I don't know why the original issue was using annotations that way.

**Comment by igorgsh** [comment]
Ok. I have removed all annotation. It is still failed. Then I have register module:
        mapper.registerModule(new com.fasterxml.jackson.datatype.jsr310.JSR310Module());
It is working! But module  JSR310Module() is deprecated. What module should I use instead of it?

**Comment by igorgsh** [comment]
Ops. I have found JavaTime() module. Thank you. You can close this issue
