### ISSUE TITLE
Serialization of LocalDateTime if the mapper has a configured timezone

### ISSUE THREAD

**Issue by thaitzer** [FasterXML/jackson-datatype-jsr310#81]
Hi!
First - I am sorry for starting a separate issue but I could not find anything regarding the matter with a quick search.

What is the intended behavior when a mapper has a configured timezone that differs from the default timezone and a Java 8 date-time object is serialized?

The behavior for a java.util.Date is that it is converted to the mapper-timezone, while a LocalDateTime object will not be converted. I would have expected that a LocalDateTime object is also converted - as there is a specific timezone configured for the mapper. But people might argue that - as it is a LocalDateTime it should not be converted ... 

However I am quite sure that there is a bug for ZonedDateTime as you can see from the output below:

The example code below results in the following output: 

   `{"creationDate":"2016-08-25 11:13:02","zonedDate":"2016-08-25 11:13:02","date":"2016-08-25 09:13:02"}`

```
ObjectMapper mapper = new ObjectMapper();
mapper.setTimeZone(TimeZone.getTimeZone("UTC"));
mapper.findAndRegisterModules();
try {
  System.out.println(mapper.writeValueAsString(new TestDate()));
} catch (JsonProcessingException e) {
  // TODO Auto-generated catch block
  e.printStackTrace();
}
```

and TestDate:

```
public class TestDate {
@JsonFormat(shape = Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
private LocalDateTime creationDate = LocalDateTime.now();
@JsonFormat(shape = Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
private ZonedDateTime zonedDate = ZonedDateTime.now(ZoneId.of("Europe/Vienna")); // this is actually my default
@JsonFormat(shape = Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
private Date date = new Date();
public ZonedDateTime getZonedDate() {
  return zonedDate;
}
public void setZonedDate(ZonedDateTime zonedDate) {
  this.zonedDate = zonedDate;
}
public Date getDate() {
  return date;
}
public void setDate(Date date) {
  this.date = date;
}
public LocalDateTime getCreationDate() {
  return creationDate;
}
public void setCreationDate(LocalDateTime creationDate) {
  this.creationDate = creationDate;
}
}
```

**Comment by cowtowncoder** [comment]
Can't give a full answer right away, but some notes:

1. `java.util.Date` does not have a timezone associated with it, ever -- it's just a `long` timestamp. Timezone is associated if serializing, in which case contextual timezone should be used
2. Local date/time values are similar to `java.util.Date` in that they presumably also have no timezone associated... but: unlike with `Date`, internal storage is such, I think, that date/time components MAY be used without timezone, so association is not necessarily needed
3. Jackson should never use JVM default timezone for anything; this is a design decision, and should be followed by all components. If user does want to use that timezone, she should set `ObjectMapper` default timezone to the JVM default timezone explicitly

To elaborate on (2), I think that serialization should be possible without any timezone information (and deserialization); but if so, serialization MUST NOT contain any timezone indicator. Conversely, if timezone indicator is needed, then timezone needs to be associated... and that should be the timezone configured for `ObjectMapper`.

Not sure if this helps, but I thought I'll try to add some relevant background info.
