### ISSUE TITLE
If the JsonFormat pattern is all numeric, the InstantDeserializer will do the wrong thing

### ISSUE THREAD

**Issue by ubik2** [FasterXML/jackson-datatype-jsr310#89]
When using an annotated pattern, as below, the InstantDeserializer attempts to parse it as a number.

This alternate parsing (and similar cleanup of timezone) should only occur when using one of the default DateTimeFormatters.

```
        @JsonFormat(pattern="yyyyMMddHHmmss",
                shape=JsonFormat.Shape.STRING,
                timezone="UTC")
        public ZonedDateTime value;
```

**Comment by cowtowncoder** [comment]
Fixed, as per #88.
