### ISSUE TITLE
Threetenbp

### ISSUE THREAD

**Issue by cbornet** [FasterXML/jackson-datatype-jsr310#90]
The [threetenbp](https://github.com/joschi/jackson-datatype-threetenbp) fork doesn't seem very lively and hasn't been updated since jackson 2.6.4.
Could FasterXML provide its own threetenbp implementation or maintain this one ?
I understand this is a lot of work but threetenbp is now the recommended date lib for apps that can't upgrade to JDK8 (eg. android) so it would be great to have official support.

**Comment by cowtowncoder** [comment]
@cbornet more the merrier and I would not be against support, but right now limitation is time. So I could definitely help, and take of releasing new versions as part of standard release process. But I would need help with transition. Do you know authors `jackson-datatype-threetenbdp` to contact.

Also: I'll move this issue as I am reorganizing modules a bit.
