### ISSUE TITLE
Serialization doesn't work as expected

### ISSUE THREAD

**Issue by kopax** [FasterXML/jackson-datatype-jsr310#91]
I am replacing JodaTime by JSR310 and the module of JodaTime() was working fine.

I am trying to reconfigure the serialization of my dates in my spring-boot application.

I can't keep both so I am looking for a way to serialize/deserialize my date to ISO 8601.

I followed the advices here but this doesn't help : 
http://lewandowski.io/2016/02/formatting-java-time-with-spring-boot-using-json/

This is my `JacksonConfig.java` with the `objectMapper`:
    
```java
    @Configuration
	public class JacksonConfig extends RepositoryRestMvcConfiguration {
	
		private static final Logger logger = LoggerFactory.getLogger(JacksonConfig.class);
		public static final DateTimeFormatter FORMATTER = ofPattern("dd::MM::yyyy");
	
		@Bean
		// Override and Primary due to bug: https://github.com/spring-projects/spring-boot/issues/6529
		@Override
		@Primary
		public ObjectMapper objectMapper() {
			ObjectMapper mapper = new ObjectMapper();
			mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
			mapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, true);
			mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
			JavaTimeModule javaTimeModule = new JavaTimeModule();
			javaTimeModule.addSerializer(LocalDate.class, new LocalDateSerializer());
			javaTimeModule.addDeserializer(LocalDate.class, new LocalDateDeserializer());
			mapper.registerModule(javaTimeModule);
			return mapper;
		}
	
		public class LocalDateSerializer extends JsonSerializer<LocalDate> {
			@Override
			public void serialize(LocalDate value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
				gen.writeString(value.format(FORMATTER));
			}
		}
		public class LocalDateDeserializer extends JsonDeserializer<LocalDate> {
			@Override
			public LocalDate deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
				return LocalDate.parse(p.getValueAsString(), FORMATTER);
			}
		}
	}
```

The bean get instanciated but the `serialize` and `deserialize` never get called.

I've also tried the `JavaTimeModule` without the custom serializer/deserializer, it's also not working.

It seems to have no effect at all.

Is there a way to debug this a bit more ?

**Comment by cowtowncoder** [comment]
Ok so it does not work in what way? And with which Jackson version?

**Comment by kopax** [comment]
It does not work

timestamp are serialized like this 

    "creationDateTime": {
        "nano": 0,
        "epochSecond": 1481498638
    },

LocalDateTime like this 

    "foundingDateTime": {
        "year": 2016,
        "month": "JUNE",
        "chronology": {
            "calendarType": "iso8601",
            "id": "ISO"
        },
        "era": "CE",
        "dayOfYear": 180,
        "dayOfWeek": "TUESDAY",
        "leapYear": true,
        "dayOfMonth": 28,
        "monthValue": 6
    },

**Comment by kopax** [comment]
I resolve this problem by completely disabling my objectMapper configuration, now I have date like 

```
"creationDateTime": {
"content": "2016-12-12T01:39:25Z"
}
```

It's a bit sad that I cannot customize the serialization.

**Comment by cowtowncoder** [comment]
@kopax Output as a POJO would only occur if this module (`jackson-datatype-jsr310`) was not registered for some reason.
So I think registration is missing/failing somehow.

As to overriding formatting: `@JsonFormat` should allow use of custom format Strings for this module too, not just JDK `Date` and `Calendar`. This annotation would be added to property/-ies in question.

**Comment by kopax** [comment]
@cowtowncoder By removing my JacksonConfig with the customization of the ObjectMapper, I was able to get the serialization working straight away.

I think there is something wrong if you use spring-hateoas+spring-data , they use their own ObjectMapper, I have read the documentation and example on the internet and didn't found an expected working way to configure it.

**Comment by forbode** [comment]
Has there been any additional info on this? 

I have the same issue. I CANNOT find any way to add custom ser/des modules to the halObjectMapper. I've tried Jackson2ObjectMapperBuilder, @POstConstruct on the "halObjectMapper" instance, @Primary bean... nothing works. The halObjectMapper ignores my modules.

I can, however, register modules to the standard objectMapper and all of my @JsonTest's work just fine. Point being that the modules, which I am trying to register, work just fine.

**Comment by cowtowncoder** [comment]
Not sure what else could be done on Jackson side: please re-file for remaining issues if necessary, with suggestions on improvements / changes.
