### ISSUE TITLE
Missing constructor in OffsetDateTimeSerializer class

### ISSUE THREAD

**Issue by LudovitVarga** [FasterXML/jackson-datatype-jsr310#92]
I want serialize all instances of OffsetDateTime with UTC timezone, but i can't instantiate OffsetDateTime with local timezone (code is out of my reach).

With other Java 8 time classes, this is not a problem:
``` java
JavaTimeModule javaTimeModule = new JavaTimeModule();

javaTimeModule.addSerializer(
		ZonedDateTime.class,
		new ZonedDateTimeSerializer(DateTimeFormatter.ISO_ZONED_DATE_TIME.withZone(ZoneOffset.UTC))
);
```

But this is with OffsetDateTime not possible because this code won't compile:
``` java
JavaTimeModule javaTimeModule = new JavaTimeModule();

javaTimeModule.addSerializer(
		OffsetDateTime.class,
		new OffsetDateTimeSerializer(DateTimeFormatter.ISO_OFFSET_DATE_TIME.withZone(ZoneOffset.UTC))
);
```

OffsetDateTimeSerializer class need new constructor with DateTimeFormatter, similar to constructor in ZonedDateTimeSerializer for example:
``` java
public ZonedDateTimeSerializer(DateTimeFormatter formatter) {
    super(ZonedDateTime.class, dt -> dt.toInstant().toEpochMilli(),
          ZonedDateTime::toEpochSecond, ZonedDateTime::getNano,
          formatter);
}
```

**Comment by cowtowncoder** [comment]
Typically forcing of a timezone should not need to rely on serializer being used but rather on configuration. Would it not work instead by either using:

* `@JsonFormat(timezone="UTC")`
* Equivalent configOverride, using `ObjectMapper.configOverride(ZonedDateTime.class)` (and then method for constructing `JsonFormat.Value` object with timezone default)

(second part I haven't test; config overrides added in 2.8, but requires support from datatype serializers so there may be some wiring missing)

I am not against adding constructors if absolutely necessary, but (de)serializers provided by modules should mostly be black boxes that users need not modify or instantiate.
So I'd like to first make sure additional access is necessary.

**Comment by LudovitVarga** [comment]
> Typically forcing of a timezone should not need to rely on serializer being used but rather on configuration.

Yes but this module ignores if i set timezone via "objectMapper.setTimeZone(tz)".

> @JsonFormat(timezone="UTC")`

I can't use annotation because i can't change classes of serialized objects, also i want set timezone globally for all instances of OffsetDateTime.

> I am not against adding constructors if absolutely necessary, but (de)serializers provided by modules should mostly be black boxes that users need not modify or instantiate.

I agree but other serializers in this module have public constructor with DateTimeFormatter, so API of serializers is inconsistent and also against your black box statement.
And if serializers are black boxes, they should use timezone from ObjectMapper, so i don't need to worry about anything inside module, only global mapper configuration.

Config override is new for me and i will try it for future development, but in my current solution is not possible update to 2.8+

**Comment by cowtowncoder** [comment]
@LudovitVarga one note on not being able to use 2.8: note that any constructor additions would go in `master`, that is, for 2.9. So even if things are fixed this will not be done for older versions.

But I would be interested in part of "module is not using configured timezone": if this is the case, it sounds like a bug to me.
