### ISSUE TITLE
Problem parsing time if milliseconds not available

### ISSUE THREAD

**Issue by jnovotny** [FasterXML/jackson-datatype-jsr310#93]
Usually I get dates like 2017-02-25T06:36:21.530

And I use the following annotations:

@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS")
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonProperty

However this fails if the time provided has no milliseconds e.g. 2017-02-25T06:36:21
Is there a way to specify to just ignore milliseconds in this case use 000 for instance?

Thanks, Jason

**Comment by cowtowncoder** [comment]
Since deserializer uses standard format string that Java8 date/time supports, with no modifications, I think this comes down to trying to either figure out suitable string to use; or to custom deserializer.
I do not know if format string allows for such optional part; I hope someone else does?

**Comment by magaton** [comment]
Hit the same problem! Optional milliseconds don't seem to work
@jsonformat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss[.SSS]")

**Comment by cowtowncoder** [comment]
With self-contained unit test may be refiled at:

https://github.com/FasterXML/jackson-modules-java8/issues
